# Generated by Django 4.2.2 on 2023-06-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
