import "./globals.css";
import "@/styles/fonts/style.css";

import { Providers } from "@/redux/provider";
import { AuthProvider } from "@/contexts/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProvider> 
              {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
